{{- include "ffc-helm-library.container-secret" (list . "ffc-pact-broker.container-secret") -}}
{{- define "ffc-pact-broker.container-secret" -}}
stringData:
  PACT_BROKER_DATABASE_USERNAME: {{ quote .Values.postgresService.postgresUsername }}
  PACT_BROKER_DATABASE_PASSWORD: {{ quote .Values.postgresService.postgresPassword }}
  PACT_BROKER_BASIC_AUTH_USERNAME: {{ quote .Values.container.authUsername }}
  PACT_BROKER_BASIC_AUTH_PASSWORD: {{ quote .Values.container.authPassword }}
{{- end -}}