{{- include "ffc-helm-library.deployment" (list . "ffc-pact-broker.deployment") -}}
{{- define "ffc-pact-broker.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-pact-broker.container") }}
{{- end -}}
